### ISSUE TITLE
Sequencing

### ISSUE THREAD

**Issue by afoster28** [afoster28/opt_portfolio_variance#14]
- Ensure appropriate sequencing for options being input
- Calculate mean, variance and standard deviation after every option gets added to the portfolio
- Display mean, variance and standard deviation before any option gets added too - should be zero
- Save output as CSV: trade number (including 0), mean, variance, standard deviation columns

**Comment by afoster28** [comment]
More details on mean, variance, standard deviation calculations:

- Calculate portfolio payout as the sum of payout of all options (currently stored as optionPayouts vector in the code) per scenario price
   For example using:
    // Function to calculate the sum of values per price (row)
    std::vector<double> calculateRowSum(const std::vector<std::vector<double>>& payouts) const {
        std::vector<double> rowSums;
        rowSums.reserve(payouts.size());

        for (const auto& row : payouts) {
            double rowSum = 0.0;
            for (const auto& value : row) {
                rowSum += value;
            }
            rowSums.push_back(rowSum);
        }

        return rowSums;
    }
- Do for all prices -> generate portfolio payout vector
- Mean, variance and standard deviation should be applied on the portfolio payout vector
- The process needs to be repeated whenever an option is added to the portfolio

![Screenshot 2024-01-24 200249](https://github.com/afoster28/opt_portfolio_variance/assets/128722683/5376a58f-343c-4ce3-87f7-45b3574a7acb)

**Comment by secoman** [comment]
1.
[Ensuring 1.txt](https://github.com/afoster28/opt_portfolio_variance/files/14144069/Ensuring.1.txt)
[Ensuring Notes 1.1.txt](https://github.com/afoster28/opt_portfolio_variance/files/14144070/Ensuring.Notes.1.1.txt)

2.
[Metrics 2.txt](https://github.com/afoster28/opt_portfolio_variance/files/14144073/Metrics.2.txt)
[Metrics Notes 2.1.txt](https://github.com/afoster28/opt_portfolio_variance/files/14144074/Metrics.Notes.2.1.txt)

3.
[Saving CSV Notes 3.txt](https://github.com/afoster28/opt_portfolio_variance/files/14144078/Saving.CSV.Notes.3.txt)
[Saving CSV Notes 3.1.txt](https://github.com/afoster28/opt_portfolio_variance/files/14144079/Saving.CSV.Notes.3.1.txt)

**Comment by secoman** [comment]
[Updated Metrics.txt](https://github.com/afoster28/opt_portfolio_variance/files/14144120/Updated.Metrics.txt)

**Comment by secoman** [comment]
[Integrated fully 1.txt](https://github.com/afoster28/opt_portfolio_variance/files/14145926/Integrated.fully.1.txt)
[Integrated fully notes 1.txt](https://github.com/afoster28/opt_portfolio_variance/files/14145936/Integrated.fully.notes.1.txt)
