### ISSUE TITLE
Create separate test program that calculates a matrix with % differences based on generated output result_matrix.csv and relevant table in output_small.txt

### ISSUE THREAD

**Issue by afoster28** [afoster28/opt_portfolio_variance#23]

**Comment by secoman** [comment]
[Formatting_Differencing.txt](https://github.com/afoster28/opt_portfolio_variance/files/14157172/Formatting_Differencing.txt)

**Comment by afoster28** [comment]
Nice initial version. I'm getting the following error:

An error occurred: stod

**Comment by afoster28** [comment]
Can you make the inputs dynamic, i.e. ask the user to provide the name of the model output and expected output?

Change result to decimal instead of * 100 and limit to 2 decimal places

**Comment by secoman** [comment]
[Updated Formatting_Differencing.txt](https://github.com/afoster28/opt_portfolio_variance/files/14157249/Updated.Formatting_Differencing.txt)

**Comment by afoster28** [comment]
Doesn't compile - please check

**Comment by afoster28** [comment]
Enter the name of the model output CSV file: result_matrix.csv
Enter the name of the expected output CSV file: output_small.txt
Error converting string to double: stod
Error converting string to double: stod
Error converting string to double: stod
Error converting string to double: stod
Error converting string to double: stod
Error converting string to double: stod
Difference matrix has been saved to difference_matrix.csv

**Comment by secoman** [comment]
// Improved readMatrixFromCSV (tried to handle errors) needs integrating
std::vector<std::vector<double>> readMatrixFromCSV(const std::string& filename) {
    std::vector<std::vector<double>> matrix;
    std::ifstream file(filename);
    std::string line;
    
    while (std::getline(file, line)) {
        std::vector<double> row;
        std::istringstream ss(line);
        std::string value;
        
        while (std::getline(ss, value, ',')) {
            try {
                row.push_back(std::stod(value));
            } catch (const std::invalid_argument& ia) {
                // Handling or logging invalid argument error
                continue; // Skipping this value
            }
        }
        
        matrix.push_back(row);
    }
    
    return matrix;
}

int main() {
    std::string inputFilename, expectedFilename;
    std::cout << "Enter the input CSV filename: ";
    std::cin >> inputFilename;
    std::cout << "Enter the expected output filename: ";
    std::cin >> expectedFilename;

    // Use these filenames where needed in the rest of opt_v9
}

**Comment by afoster28** [comment]
Still doesn't compile - can you fix and upload the entire script?

**Comment by secoman** [comment]
[Comparison.txt](https://github.com/afoster28/opt_portfolio_variance/files/14157831/Comparison.txt)


Having trouble with the error:

Enter model output file name: result_matrix.csv
Enter expected output file name: output_small.txt
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod

**Comment by secoman** [comment]
[diff.txt](https://github.com/afoster28/opt_portfolio_variance/files/14157855/diff.txt)

Fixed it. It should work.

**Comment by secoman** [comment]
![image](https://github.com/afoster28/opt_portfolio_variance/assets/128595426/302a1577-7ff8-4fa1-b853-cb5f2ce3e6c6)
[difference_matrix.csv](https://github.com/afoster28/opt_portfolio_variance/files/14157868/difference_matrix.csv)

**Comment by secoman** [comment]
[DIFF.xlsx](https://github.com/afoster28/opt_portfolio_variance/files/14158597/DIFF.xlsx)
