### ISSUE TITLE
Refine input

### ISSUE THREAD

**Issue by afoster28** [afoster28/opt_portfolio_variance#6]
- Create easy-to-use API: using the class, adding options, resetting the portfolio, retrieving variance
- Check API aligns with official input data provided

**Comment by secoman** [comment]
#include <iostream>
#include <vector>
#include <cmath>
#include <numeric> // for std::accumulate

// ... [BlackScholes class definition remains the same] ...

class Portfolio {
private:
    std::vector<BlackScholes> options;

public:
    // Add a BlackScholes option to the portfolio
    void addOption(const BlackScholes& option) {
        options.push_back(option);
    }

    // Reset the portfolio by clearing all options
    void resetPortfolio() {
        options.clear();
    }

    // Calculate and return the variance of the portfolio
    double getVariance() const {
        double mean = std::accumulate(options.begin(), options.end(), 0.0, 
                                      [](double sum, const BlackScholes& op) { return sum + op.calculateOptionPrice(); }) 
                      / options.size();

        double variance = std::accumulate(options.begin(), options.end(), 0.0, 
                                          [mean](double sum, const BlackScholes& op) {
                                              double diff = op.calculateOptionPrice() - mean;
                                              return sum + diff * diff;
                                          }) 
                         / options.size();

        return variance;
    }
};

int main() {
    // Create a portfolio
    Portfolio myPortfolio;

    // Add options to the portfolio
    myPortfolio.addOption(BlackScholes("L", "C", 5000.0, 4800.0, 0.05, 0.2, 60.0, 10.0));
    // Add more options as needed

    // Calculate and print portfolio variance
    std::cout << "Portfolio Variance: " << myPortfolio.getVariance() << std::endl;

    // Reset the portfolio
    myPortfolio.resetPortfolio();

    // [Code for handling official input data]

    return 0;
}

**Comment by secoman** [comment]
#include <iostream>
#include <sstream>
#include <cmath>
#include <vector>
#include <numeric>

class BlackScholes {
private:
    std::string dir;
    std::string optType;
    double S;  // Spot price of the underlying asset
    double K;  // Strike price of the option
    double r;  // Risk-free interest rate
    double sigma;  // Volatility of the underlying asset
    double T;  // Time to expiration of the option
    double Q; // Trade volume

public:
    BlackScholes(std::string direction, std::string optionType, double spotPrice, double strikePrice, double interestRate, double volatility, double timeToExpiration, double quantity)
        : dir(direction), optType(optionType), S(spotPrice), K(strikePrice), r(interestRate), sigma(volatility), T(timeToExpiration), Q(quantity) {}

    double calculateOptionPrice() {
        T = T / 365;

        double d1 = (log(S / K) + (r + 0.5 * pow(sigma, 2)) * T) / (sigma * sqrt(T));
        double d2 = d1 - sigma * sqrt(T);

        double dir_num = (dir == "L") ? 1 : -1;

        if (optType == "C") {
            return Q * dir_num * (S * normalDistribution(d1) - K * exp(-r * T) * normalDistribution(d2));
        } else if (optType == "P") {
            return Q * dir_num * (K * exp(-r * T) * normalDistribution(-d2) - S * normalDistribution(-d1));
        }

        return 0.0;
    }

private:
    double normalDistribution(double x) {
        static const double invSqrt2Pi = 0.3989422804014337;
        return 0.5 * (1.0 + erf(x * invSqrt2Pi));
    }
};

class Portfolio {
private:
    std::vector<BlackScholes> options;

public:
    void addOption(const BlackScholes& option) {
        options.push_back(option);
    }

    void resetPortfolio() {
        options.clear();
    }

    double getVariance() const {
        if (options.empty()) return 0.0;

        double mean = std::accumulate(options.begin(), options.end(), 0.0, 
                                      [](double sum, const BlackScholes& op) { return sum + op.calculateOptionPrice(); }) 
                      / options.size();

        double variance = std::accumulate(options.begin(), options.end(), 0.0, 
                                          [mean](double sum, const BlackScholes& op) {
                                              double diff = op.calculateOptionPrice() - mean;
                                              return sum + diff * diff;
                                          }) 
                         / options.size();

        return variance;
    }
};

int main() {
    Portfolio myPortfolio;

    myPortfolio.addOption(BlackScholes("L", "C", 5000.0, 4800.0, 0.05, 0.2, 60.0, 10.0));
    // Add more options as needed

    double portfolioVariance = myPortfolio.getVariance();
    std::cout << "Portfolio Variance: " << portfolioVariance << std::endl;

    myPortfolio.resetPortfolio();

    // Additional code to handle official input data can be added here.

    return 0;
}

**Comment by secoman** [comment]
- **To refactor the input so that users can insert lines of parameters, you can uncomment and modify the section of the code that reads user input**

#include <iostream>
#include <sstream>
#include <cmath>
#include <vector>
#include <numeric>

class BlackScholes {
private:
    std::string dir;
    std::string optType;
    double S;  // Spot price of the underlying asset
    double K;  // Strike price of the option
    double r;  // Risk-free interest rate
    double sigma;  // Volatility of the underlying asset
    double T;  // Time to expiration of the option
    double Q; // Trade volume

public:
    BlackScholes(std::string direction, std::string optionType, double spotPrice, double strikePrice, double interestRate, double volatility, double timeToExpiration, double quantity)
        : dir(direction), optType(optionType), S(spotPrice), K(strikePrice), r(interestRate), sigma(volatility), T(timeToExpiration), Q(quantity) {}

    double calculateOptionPrice() {
        T = T / 365;

        double d1 = (log(S / K) + (r + 0.5 * pow(sigma, 2)) * T) / (sigma * sqrt(T));
        double d2 = d1 - sigma * sqrt(T);

        double dir_num = (dir == "L") ? 1 : -1;

        if (optType == "C") {
            return Q * dir_num * (S * normalDistribution(d1) - K * exp(-r * T) * normalDistribution(d2));
        } else if (optType == "P") {
            return Q * dir_num * (K * exp(-r * T) * normalDistribution(-d2) - S * normalDistribution(-d1));
        }

        return 0.0;
    }

private:
    double normalDistribution(double x) {
        static const double invSqrt2Pi = 0.3989422804014337;
        return 0.5 * (1.0 + erf(x * invSqrt2Pi));
    }
};

class Portfolio {
private:
    std::vector<BlackScholes> options;

public:
    void addOption(const BlackScholes& option) {
        options.push_back(option);
    }

    void resetPortfolio() {
        options.clear();
    }

    double getVariance() const {
        if (options.empty()) return 0.0;

        double mean = std::accumulate(options.begin(), options.end(), 0.0, 
                                      [](double sum, const BlackScholes& op) { return sum + op.calculateOptionPrice(); }) 
                      / options.size();

        double variance = std::accumulate(options.begin(), options.end(), 0.0, 
                                          [mean](double sum, const BlackScholes& op) {
                                              double diff = op.calculateOptionPrice() - mean;
                                              return sum + diff * diff;
                                          }) 
                         / options.size();

        return variance;
    }
};

int main() {
    Portfolio myPortfolio;
    std::string userInput;

    while (true) {
        std::cout << "Enter option parameters (dir, optType, S, K, r, sigma, T, Q), or 'exit' to finish: ";
        std::getline(std::cin, userInput);

        if (userInput == "exit") {
            break;
        }

        std::istringstream input_stream(userInput);
        std::string dir, optType;
        double S, K, r, sigma, T, Q;

        if (input_stream >> dir >> optType >> S >> K >> r >> sigma >> T >> Q) {
            myPortfolio.addOption(BlackScholes(dir, optType, S, K, r, sigma, T, Q));
            std::cout << "Option added to portfolio." << std::endl;
        } else {
            std::cerr << "Invalid input. Please enter all parameters correctly." << std::endl;
        }
    }

    double portfolioVariance = myPortfolio.getVariance();
    std::cout << "Portfolio Variance: " << portfolioVariance << std::endl;

    // Additional code for other functionalities can be added here

    return 0;
}

**For example: a valid input could be: L C 5000.0 4800.0 0.05 0.2 60.0 10.0.**

**Comment by secoman** [comment]
**This version will allow users to input option parameters in the format optType, dir, K, T, Q and use default values for the Spot Price (S), Risk-free Interest Rate (r), and Volatility (sigma)**

**_In this program_:** 

- The user is prompted to enter the parameters for each option in the specified format (optType, dir, K, T, Q).

- The parameters are read and used to create a BlackScholes object with the default values for S, r, and sigma.

- The created BlackScholes object is added to the Portfolio.

- The user can enter as many options as desired and type exit to finish inputting data.

- After exiting the input loop, the program calculates and displays the variance of the portfolio.

**_Here goes the code:_**

[WithInput.txt](https://github.com/afoster28/opt_portfolio_variance/files/13855000/WithInput.txt)

**Comment by secoman** [comment]
[Revised_1(C++).txt](https://github.com/afoster28/opt_portfolio_variance/files/13873596/Revised_1.C%2B%2B.txt)

Here is the revised version.


![image](https://github.com/afoster28/opt_portfolio_variance/assets/128595426/40671d68-c15b-4311-8401-6f11040a27d4)


It should look like this.

**Comment by secoman** [comment]
![image](https://github.com/afoster28/opt_portfolio_variance/assets/128595426/606a0212-1a4a-4371-9d29-afb37741e2c7)
[Revised_2(C++).txt](https://github.com/afoster28/opt_portfolio_variance/files/13873870/Revised_2.C%2B%2B.txt)

We should enter the parameters with space after the comma. For example: **C, L, 4800, 60, 10**
