### ISSUE TITLE
Portfolio variance fix

### ISSUE THREAD

**Issue by afoster28** [afoster28/opt_portfolio_variance#7]
- Check why portfolio variance displays 0
- Add a feature that gives us the possibility of temporarily showing resulting option prices in order to make sure that isn't causing issues downstream

**Comment by secoman** [comment]
[codes with debug-option prices.txt](https://github.com/afoster28/opt_portfolio_variance/files/13943369/codes.with.debug-option.prices.txt)

Here is the updated version.
Could you check if it is correct ? Thanks.

![image](https://github.com/afoster28/opt_portfolio_variance/assets/128595426/92d59bc9-d064-46a5-b07c-3feb31d6b698)

It should look like this.

**Comment by afoster28** [comment]
Nice changes - now we can see options prices too. I get the same when running locally.

The prices look a bit off: for the first one we should expect about $3000 (factoring in quantity and direction of course).

Second point is that these prices are duplicated in the output above - worth checking if the same happening in processing for portfolio variance.

Lastly, portfolio variance still shows ~0 so need to check that.
